const SUPABASE_URL="https://lejoeywrtgxyoilrzrwg.supabase.co",SUPABASE_KEY="sb_publishable_Zfzv_p6vzjQpIwd8AYuasg_HVMxYwSN";
let wines=[],history=[],tastings=[],purchaseLots=[],session=null,activePriority=null,activeType="Tutti",activeSort="vintage-asc",activeHistoryType="all",lastOpen=null,pendingAnalysisPhoto=null;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function headers(json=true){const h={apikey:SUPABASE_KEY};if(session?.access_token)h.Authorization=`Bearer ${session.access_token}`;if(json)h["Content-Type"]="application/json";return h}function saveSession(s){session=s;s?localStorage.setItem("cdp_session",JSON.stringify(s)):localStorage.removeItem("cdp_session")}function cachedSession(){try{return JSON.parse(localStorage.getItem("cdp_session")||"null")}catch{return null}}
async function refreshSession(){if(!session?.refresh_token)return false;const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:headers(),body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok)return false;saveSession(await r.json());return true}async function request(path,opt={}){let r=await fetch(SUPABASE_URL+path,{...opt,headers:{...headers(opt.body!==undefined),...(opt.headers||{})}});if(r.status===401&&await refreshSession())r=await fetch(SUPABASE_URL+path,{...opt,headers:{...headers(opt.body!==undefined),...(opt.headers||{})}});if(!r.ok)throw new Error((await r.text())||`Errore ${r.status}`);if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const fmt=n=>Number(n||0).toLocaleString("it-IT",{maximumFractionDigits:2});const img=w=>w.official_image_url||w.bottle_image_url||w.personal_image_url||w.label_image_url;function market(w){if(w.market_value_min==null)return"—";return w.market_value_max&&w.market_value_max!==w.market_value_min?`€${fmt(w.market_value_min)}–${fmt(w.market_value_max)}`:`€${fmt(w.market_value_min)}`}function windowText(w){return w.drink_from&&w.drink_to?`${w.drink_from}–${w.drink_to}`:(w.notes?.match(/Finestra consigliata:\s*(.*)/i)?.[1]||"—")}function buy(w){return w.acquisition_type==="Regalo"?"Regalo":w.purchase_price==null?"—":`€${fmt(w.purchase_price)}`}function valueTotal(){return wines.reduce((s,w)=>s+w.quantity*Number(w.market_value_max??w.market_value_min??0),0)}function investment(){return wines.reduce((s,w)=>s+w.quantity*Number(w.purchase_price||0),0)}
function stats(){const avail=wines.filter(w=>w.quantity>0),count=p=>avail.filter(w=>w.priority===p).reduce((s,w)=>s+w.quantity,0),total=avail.reduce((s,w)=>s+w.quantity,0),current=valueTotal(),paid=investment();$("#total").textContent=total;$("#labels").textContent=avail.length;$("#value").textContent=`€${fmt(current)}`;$("#yellowCount").textContent=count("yellow");$("#greenCount").textContent=count("green");$("#orangeCount").textContent=count("orange");$("#aiBottleCount").textContent=total;$("#aiYellow").textContent=count("yellow");$("#aiGreen").textContent=count("green");$("#aiOrange").textContent=count("orange");$("#collValue").textContent=`€${fmt(current)}`;$("#investment").textContent=`€${fmt(paid)}`;$("#appreciation").textContent=paid?`Differenza / apprezzamento: ${current-paid>=0?"+":"-"}€${fmt(Math.abs(current-paid))}`:"Differenza non disponibile: mancano prezzi di acquisto.";$("#collBottles").textContent=total;renderComposition()}
function render(){const q=$("#search").value.toLowerCase().trim();const arr=wines.filter(w=>w.quantity>0&&(activeType==="Tutti"||(activeType==="Bianco e Bollicine"?["Bianco e Bollicine","Bianchi e Bollicine"].includes(w.category):w.category===activeType))&&(!activePriority||w.priority===activePriority)&&(!q||(w.name+" "+(w.producer||"")+" "+(w.vintage||"")).toLowerCase().includes(q))).sort((a,b)=>{if(activeSort==="producer-asc")return (a.producer||a.name).localeCompare(b.producer||b.name,"it");if(activeSort==="value-desc")return Number(b.market_value_max??b.market_value_min??0)-Number(a.market_value_max??a.market_value_min??0)||a.name.localeCompare(b.name);const av=a.vintage==null?Infinity:Number(a.vintage),bv=b.vintage==null?Infinity:Number(b.vintage);return (activeSort==="vintage-desc"?bv-av:av-bv)||a.name.localeCompare(b.name,"it")});$("#list").innerHTML=arr.map(w=>`<article class="wine-card" data-wine="${w.id}"><i class="dot ${w.priority} statusdot"></i><div class="photo">${img(w)?`<img src="${esc(img(w))}" alt="${esc(w.name)}">`:"🍾"}</div><div class="body"><div class="producer">${esc(w.producer||w.category)}</div><div class="name">${esc(w.name)}</div><div class="vintage">${w.vintage??"S.A."}</div><div class="foot"><span class="qty">Disponibili <b>${w.quantity}</b></span><span>${market(w)}</span></div></div></article>`).join("")||'<div class="panel muted" style="grid-column:1/-1">Nessuna bottiglia con questi filtri.</div>';$$('[data-wine]').forEach(c=>c.onclick=()=>showWine(c.dataset.wine));stats()}
function regionOf(w){return typeof w.region==="string"&&w.region.trim()?w.region.trim():null}function dateOf(item){return item.event_date||item.purchased_at||item.acquired_at||item.created_at||item.tasting_date||item.tasted_at||item.date}function groupRows(kind){const groups={};wines.filter(w=>w.quantity>0).forEach(w=>{const key=kind==="region"?regionOf(w):w.category;if(!key)return;groups[key]=(groups[key]||{quantity:0,value:0,wines:[]});groups[key].quantity+=Number(w.quantity||0);groups[key].value+=Number(w.quantity||0)*Number(w.market_value_max??w.market_value_min??0);groups[key].wines.push(w)});return groups}function showCollectionGroup(kind,key){const rows=groupRows(kind)[key];if(!rows)return;openModal(`<h2>${esc(key)}</h2><p class="muted">${rows.quantity} bottiglie · €${fmt(rows.value)}</p>${rows.wines.map(w=>`<div class="history-item"><b>${esc(w.name)}</b><div class="muted">${esc(w.producer||"Produttore non indicato")} · ${w.quantity} · ${market(w)}</div></div>`).join("")}`)}
function renderComposition(){const a=wines.filter(w=>w.quantity>0),tot=a.reduce((s,w)=>s+w.quantity,0)||1,groups=groupRows("category"),regions=groupRows("region");$("#composition").innerHTML=Object.entries(groups).map(([k,v])=>`<button class="composition-row" data-group="category" data-key="${esc(k)}"><b>${esc(k)}</b><span>${v.quantity} · ${Math.round(v.quantity/tot*100)}%</span></button>`).join("")||'<p class="muted">Nessun dato disponibile.</p>';$("#regionComposition").innerHTML=Object.entries(regions).map(([k,v])=>`<button class="composition-row" data-group="region" data-key="${esc(k)}"><b>${esc(k)}</b><span>${v.quantity} · €${fmt(v.value)}</span></button>`).join("")||'<p class="muted">La regione non è indicata nei dati disponibili.</p>';$$('[data-group]').forEach(b=>b.onclick=()=>showCollectionGroup(b.dataset.group,b.dataset.key));renderHistoryFilters()}
function renderHistoryFilters(){const values=key=>[...new Set(wines.map(w=>w[key]).filter(v=>v!=null&&v!==""))].sort(),eventYears=[...new Set(buildHistoryEntries().map(entry=>new Date(entry.date||0).getFullYear()).filter(year=>year>1970))].sort((a,b)=>b-a);$("#historyRegion").innerHTML='<option value="">Tutte le regioni</option>'+values("region").map(v=>`<option>${esc(v)}</option>`).join("");$("#historyCategory").innerHTML='<option value="">Tutte le tipologie</option>'+values("category").map(v=>`<option>${esc(v)}</option>`).join("");$("#historyYear").innerHTML='<option value="">Tutti gli anni</option>'+eventYears.map(v=>`<option>${v}</option>`).join("")}
function historyWine(item){return wines.find(w=>String(w.id)===String(item.wine_id))||{name:item.wine_name,vintage:item.vintage,category:item.category,region:item.region}}
function historyEntry(kind,item,wine,extra={}){return{kind,date:dateOf(item),wine,item,...extra}}
function buildHistoryEntries(){const entries=[],lotWineIds=new Set(purchaseLots.map(l=>String(l.wine_id)));purchaseLots.forEach(lot=>{const wine=historyWine(lot),kind=String(lot.acquisition_type||"").toLowerCase()==="regalo"?"receivedGift":"purchased";entries.push(historyEntry(kind,lot,wine,{price:kind==="purchased"?(lot.unit_price??lot.purchase_price??null):null}))});history.forEach(event=>{const wine=historyWine(event);if(event.event_type==="added"&&lotWineIds.has(String(event.wine_id)))return;const kind=event.event_type==="opened"?"opened":event.event_type==="gifted"||event.event_type==="damaged"||event.event_type==="removed"?"exited":event.event_type==="added"?(String(event.acquisition_type||"").toLowerCase()==="regalo"?"receivedGift":"purchased"):"event";entries.push(historyEntry(kind,event,wine,{reason:event.event_type}))});tastings.forEach(tasting=>{const wine=historyWine(tasting),stamp=new Date(dateOf(tasting)||0).getTime(),match=entries.find(entry=>entry.kind==="opened"&&String(entry.item.wine_id)===String(tasting.wine_id)&&!entry.tasting&&Math.abs(new Date(entry.date||0).getTime()-stamp)<7*86400000);if(match)match.tasting=tasting;else entries.push(historyEntry("opened",tasting,wine,{tasting}))});return entries}
function renderHistory(){const names={opened:"Aperta",purchased:"Acquistata",receivedGift:"Ricevuta in regalo",exited:"Uscita",gifted:"Regalata",damaged:"Rotta / danneggiata",removed:"Altra uscita",event:"Movimento"},region=$("#historyRegion").value,category=$("#historyCategory").value,year=$("#historyYear").value,rating=$("#historyRating").value;const entries=buildHistoryEntries().filter(x=>{const w=x.wine||{},r=x.tasting?.rating;return(activeHistoryType==="all"||x.kind===activeHistoryType)&&(!rating||String(r)===rating)&&(!region||regionOf(w)===region)&&(!category||w.category===category)&&(!year||String(new Date(x.date||0).getFullYear())===year)}).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0));$("#historyList").innerHTML=entries.slice(0,50).map(x=>{const w=x.wine||{},t=x.tasting||{},price=x.price??x.item?.price_paid??(x.kind==="purchased"?w.purchase_price:null),label=x.kind==="exited"?names[x.reason]||names.exited:names[x.kind]||names.event;return `<div class="history-item"><b>${esc(w.name||x.item?.wine_name||"Vino")} ${w.vintage??x.item?.vintage??""}</b><div class="muted">${label}${x.date?` · ${new Date(x.date).toLocaleDateString("it-IT")}`:""}${x.kind==="purchased"&&price!=null?` · €${fmt(price)}`:""}${t.rating?` · ${"★".repeat(t.rating)}${"☆".repeat(5-t.rating)}`:""}</div>${t.tasting_notes?`<div>${esc(t.tasting_notes)}</div>`:""}</div>`}).join("")||'<p class="muted">Nessun elemento con questi filtri.</p>'}
async function loadCloud(){setSync("Sincronizzo…");const [w,e,t,lots]=await Promise.all([request('/rest/v1/wines?select=*&order=vintage.asc.nullslast,name.asc',{headers:{Accept:"application/json"}}),request('/rest/v1/cellar_events?select=*&order=event_date.desc&limit=200',{headers:{Accept:"application/json"}}),request('/rest/v1/wine_tastings?select=*&order=created_at.desc&limit=200',{headers:{Accept:"application/json"}}).catch(err=>{console.error("wine_tastings",err);return[]}),request('/rest/v1/purchase_lots?select=*&order=created_at.desc&limit=500',{headers:{Accept:"application/json"}}).catch(err=>{console.error("purchase_lots",err);return[]})]);wines=w||[];history=e||[];tastings=t||[];purchaseLots=lots||[];localStorage.setItem("cdp_cloud_cache",JSON.stringify({savedAt:new Date().toISOString(),wines,history,tastings,purchaseLots}));render();renderHistory();setSync("Cloud ✓")}
function loadCache(){try{const cache=JSON.parse(localStorage.getItem("cdp_cloud_cache")||"null");if(!cache?.wines?.length)return false;wines=cache.wines;history=cache.history||[];tastings=cache.tastings||[];purchaseLots=cache.purchaseLots||[];render();renderHistory();const when=cache.savedAt?new Date(cache.savedAt).toLocaleString("it-IT",{dateStyle:"short",timeStyle:"short"}):"ultimo accesso";setSync("Offline",true);toast(`Modalità offline · dati salvati ${when}. Le modifiche richiedono connessione.`);return true}catch{return false}}
function setSync(t,off=false){$("#syncState").textContent=t;$("#syncState").classList.toggle("offline",off)}
function openModal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}function closeModal(){$("#modal").classList.add("hidden")}
function showRemoval(w){const max=Math.max(1,Number(w.quantity)||1);openModal(`<h2>Rimuovi bottiglia</h2><p class="muted">${esc(w.name)} ${w.vintage??""}</p><div class="formgrid"><label>Perché rimuovi questa bottiglia?<select id="removeReason"><option value="gifted">🎁 Regalata</option><option value="damaged">💥 Rotta / danneggiata</option><option value="removed">📦 Altra uscita</option></select></label>${max>1?`<label>Quantità da rimuovere<input id="removeQty" type="number" min="1" max="${max}" value="1" inputmode="numeric"></label>`:`<input id="removeQty" type="hidden" value="1">`}<p id="removeSummary" class="panel">Verranno rimosse 1 bottiglia dalla cantina.</p><button class="secondary" id="confirmRemove">Conferma rimozione</button></div>`);const qtyField=$("#removeQty"),summary=$("#removeSummary"),update=()=>{const qty=Math.min(max,Math.max(1,Number(qtyField.value)||1));qtyField.value=qty;summary.textContent=`Verranno rimosse ${qty} ${qty===1?"bottiglia":"bottiglie"} dalla cantina.`};qtyField.oninput=update;$("#confirmRemove").onclick=()=>removeBottle(w,Number(qtyField.value)||1,$("#removeReason").value)}
async function removeBottle(w,requestedQty,reason){const qty=Math.min(Math.max(1,requestedQty),Math.max(0,Number(w.quantity)||0));if(!qty)return;const labels={gifted:"Bottiglia regalata e rimossa dalla cantina.",damaged:"Bottiglia danneggiata rimossa dalla cantina.",removed:"Bottiglia rimossa dalla cantina."};try{await patchQty(w,w.quantity-qty);let event;try{event=(await addEvent(w,reason,-qty))?.[0]}catch(error){await patchQty(w,w.quantity);throw error}w.quantity-=qty;if(event)history.unshift(event);closeModal();render();renderHistory();toast(labels[reason]||labels.removed)}catch(error){console.error("remove bottle",error);toast("Non sono riuscito a rimuovere la bottiglia.")}}
function showWine(id){const w=wines.find(x=>x.id===id);if(!w)return;openModal(`<div class="detail-photo">${img(w)?`<img src="${esc(img(w))}">`:"🍾"}</div><h2>${esc(w.name)}</h2><p class="muted">${esc(w.producer||"")} · ${w.vintage??"S.A."} · ${esc(w.category)}</p><div class="detail-grid"><div><small>Quantità</small><b>${w.quantity}</b></div><div><small>Prezzo pagato</small><b>${buy(w)}</b></div><div><small>Valore</small><b>${market(w)}</b></div></div><div class="panel"><b><i class="dot ${w.priority}"></i> ${esc(w.status||"Stato")}</b><p class="muted">Finestra di consumo ${windowText(w)}</p>${w.notes?`<p>${esc(w.notes)}</p>`:""}</div><div class="detail-actions"><button class="winebtn" id="openDetail">− APERTA</button><button class="secondary" id="addDetail">＋ Aggiungi</button></div><div class="detail-actions"><button class="secondary" id="removeDetail">Rimuovi</button><button class="secondary" id="tasteDetail">⭐ Valuta una degustazione</button></div>`);$("#openDetail").onclick=()=>openBottle(id);$("#addDetail").onclick=()=>showAdd(true,w);$("#removeDetail").onclick=()=>showRemoval(w);$("#tasteDetail").onclick=()=>showRating(w)}
async function patchQty(w,n){return request(`/rest/v1/wines?id=eq.${w.id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({quantity:n})})}async function addEvent(w,type,delta){return request('/rest/v1/cellar_events',{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({wine_id:w.id,wine_name:w.name,vintage:w.vintage,event_type:type,quantity_delta:delta})})}
async function openBottle(id){const w=wines.find(x=>x.id===id);if(!w||w.quantity<1)return;try{await patchQty(w,w.quantity-1);let ev;try{ev=(await addEvent(w,"opened",-1))?.[0]}catch(e){await patchQty(w,w.quantity);throw e}w.quantity--;if(ev)history.unshift(ev);lastOpen=w;closeModal();render();renderHistory();toast(`${w.name}: bottiglia aperta. <button id="rateNow">Valuta ⭐</button>`);setTimeout(()=>{const b=$("#rateNow");if(b)b.onclick=()=>showRating(w)},0)}catch{toast("Operazione non riuscita.")}}
function showRating(w){openModal(`<h2>Come ti è piaciuto?</h2><p>${esc(w.name)} ${w.vintage??""}</p><div id="stars" style="font-size:38px;letter-spacing:8px;margin:22px 0">☆ ☆ ☆ ☆ ☆</div><div class="formgrid"><textarea id="tasteNotes" rows="4" placeholder="Note di degustazione (facoltative)"></textarea><label><input id="repurchase" type="checkbox"> Mi interesserebbe riacquistarlo</label><button class="primary" id="saveTaste">Salva valutazione</button></div>`);let rating=0;const starbox=$("#stars");starbox.onclick=e=>{const rect=starbox.getBoundingClientRect();rating=Math.max(1,Math.min(5,Math.ceil((e.clientX-rect.left)/rect.width*5)));starbox.textContent=[1,2,3,4,5].map(i=>i<=rating?"★":"☆").join(" ")};$("#saveTaste").onclick=async()=>{if(!rating)return toast("Scegli un voto da 1 a 5.");try{const saved=await request('/rest/v1/wine_tastings',{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({wine_id:w.id,wine_name:w.name,vintage:w.vintage,rating,tasting_notes:$("#tasteNotes").value||null,repurchase_interest:$("#repurchase").checked})});const tasting=Array.isArray(saved)?saved[0]:saved;if(tasting)tastings.unshift(tasting);closeModal();renderHistory();toast("Valutazione salvata: il Sommelier la userà per affinare le preferenze.")}catch(err){console.error("save tasting",err);toast("Non sono riuscito a salvare la valutazione.")}}}
function showAdd(existing=false,w=null){openModal(`<h2>${existing?"Aggiungi bottiglie":"Aggiungi una bottiglia"}</h2><p class="muted">Scatta una foto dell'etichetta oppure inserisci i dati manualmente.</p><div class="camera-box" id="takePhoto"><div class="cam">📷</div><b>Scatta foto etichetta</b><p class="muted">La foto viene preparata per il riconoscimento e resta disponibile come fallback.</p></div><div id="photoPreview"></div><div class="formgrid"><input id="newName" placeholder="Nome vino" value="${esc(w?.name||"")}"><input id="newProducer" placeholder="Produttore" value="${esc(w?.producer||"")}"><input id="newVintage" type="number" placeholder="Annata" value="${w?.vintage||""}"><select id="newCategory"><option>Rosso</option><option>Bianco e Bollicine</option></select><input id="newQty" type="number" min="1" value="1" placeholder="Quantità"><input id="newPrice" type="number" step="0.01" placeholder="Prezzo per bottiglia €"><select id="newAcq"><option>Acquisto</option><option>Regalo</option></select><button class="primary" id="saveBottle">${existing?"Aggiungi alla cantina":"Salva bottiglia"}</button></div><p class="muted">Riconoscimento AI automatico e ricerca foto ufficiale saranno collegati al motore Sommelier; la foto scattata ha priorità solo se non troviamo un'immagine ufficiale.</p>`);if(w)$("#newCategory").value=w.category;$("#takePhoto").onclick=()=>$("#cameraInput").click();$("#saveBottle").onclick=()=>saveBottleForm(w)}
function validNumber(value){return value!==null&&value!==undefined&&value!==""&&Number.isFinite(Number(value))}function validText(value){return typeof value==="string"&&value.trim().length>0}function enrichmentConfidence(confidence){return ["high","medium","low"].includes(String(confidence||"").toLowerCase())?String(confidence).toLowerCase():"low"}function enrichmentMatches(w,data){const name=validText(data.name||data.wine_name),producer=validText(data.producer);return name&&producer&&name.toLowerCase()===String(w.name||"").toLowerCase()&&producer.toLowerCase()===String(w.producer||"").toLowerCase()&&(!validNumber(data.vintage)||!validNumber(w.vintage)||Number(data.vintage)===Number(w.vintage))}
async function uploadEnrichmentImage(wineId,imageUrl){if(!validText(imageUrl))return null;const response=await fetch(imageUrl);if(!response.ok)throw new Error("Enrichment image download failed");const blob=await response.blob(),type=String(blob.type||response.headers.get("content-type")||"").toLowerCase(),formats={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"};if(!formats[type])throw new Error(`Unsupported enrichment image type: ${type||"unknown"}`);const path=`wines/${wineId}/official.${formats[type]}`,upload=await fetch(`${SUPABASE_URL}/storage/v1/object/wine-images/${path}`,{method:"POST",headers:{...headers(false),"Content-Type":type,"x-upsert":"true"},body:blob});if(!upload.ok)throw new Error((await upload.text())||"Image upload failed");return `${SUPABASE_URL}/storage/v1/object/public/wine-images/${path}`}
async function enrichWine(wine,isNew=false){const missing=!wine.region||!wine.appellation||!validNumber(wine.market_value_min)||!validNumber(wine.market_value_max)||!wine.official_image_url;if(!isNew&&!missing)return;toast("Completo automaticamente i dati…");try{const response=await fetch(`${SUPABASE_URL}/functions/v1/wine-enrich`,{method:"POST",headers:headers(),body:JSON.stringify({name:wine.name,producer:wine.producer||null,vintage:wine.vintage||null,appellation:wine.appellation||null})});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error||`Enrichment failed (${response.status})`);const confidence=enrichmentConfidence(data?.confidence),updates={};if(!wine.region&&validText(data?.region))updates.region=data.region.trim();if(!wine.appellation&&validText(data?.appellation))updates.appellation=data.appellation.trim();if(!validNumber(wine.market_value_min)&&validNumber(data?.market_value_min))updates.market_value_min=Number(data.market_value_min);if(!validNumber(wine.market_value_max)&&validNumber(data?.market_value_max))updates.market_value_max=Number(data.market_value_max);if(!wine.last_market_check&&(validText(data?.checked_at)||validText(data?.last_market_check)))updates.last_market_check=data.checked_at||data.last_market_check;if(!wine.official_image_url&&validText(data?.image_url)&&(confidence==="high"||(confidence==="medium"&&enrichmentMatches(wine,data)))){try{const official=await uploadEnrichmentImage(wine.id,data.image_url);if(official)updates.official_image_url=official}catch(imageError){console.error("wine-enrich image",imageError)}}if(!Object.keys(updates).length){toast("Dati della bottiglia aggiornati ✓");return}await request(`/rest/v1/wines?id=eq.${wine.id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(updates)});Object.assign(wine,updates);await loadCloud();toast("Dati della bottiglia aggiornati ✓")}catch(error){console.error("wine-enrich",error);toast("Bottiglia salvata. Alcuni dati automatici verranno completati successivamente.")}}
async function saveBottleForm(existing){const qty=Math.max(1,+$("#newQty").value||1),price=$("#newPrice").value?+$("#newPrice").value:null,acq=$("#newAcq").value;if(existing){try{await patchQty(existing,existing.quantity+qty);await request('/rest/v1/purchase_lots',{method:"POST",body:JSON.stringify({wine_id:existing.id,quantity:qty,unit_price:price,acquisition_type:acq})});await addEvent(existing,"added",qty);existing.quantity+=qty;closeModal();await loadCloud();toast(`Aggiunte ${qty} bottiglie.`);enrichWine(existing)}catch(err){console.error("add existing bottle",err);toast("Non sono riuscito ad aggiungere le bottiglie.")}return}const name=$("#newName").value.trim();if(!name)return toast("Inserisci almeno il nome del vino.");try{const created=(await request('/rest/v1/wines',{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({name,producer:$("#newProducer").value.trim()||null,vintage:+$("#newVintage").value||null,category:$("#newCategory").value,quantity:qty,acquisition_type:acq,purchase_price:price,priority:"orange",status:"Da valutare"})}))?.[0];if(created){await request('/rest/v1/purchase_lots',{method:"POST",body:JSON.stringify({wine_id:created.id,quantity:qty,unit_price:price,acquisition_type:acq})});await addEvent(created,"added",qty)}closeModal();await loadCloud();toast("Bottiglia salvata. Completo automaticamente i dati…");if(created)enrichWine(created,true)}catch(err){console.error("create bottle",err);toast("Non sono riuscito ad aggiungere la bottiglia.")}}
function recommendWines(query){const text=query.toLowerCase(),available=wines.filter(w=>w.quantity>0);if(!available.length)return[];const white=/(pesce|crudo|sushi|aperitivo|formaggi freschi|verdure|fritto|dessert|dolce|estate)/.test(text),red=/(carne|grigliata|arrosto|brasato|selvaggina|salumi|pizza|pasta|funghi|inverno)/.test(text);return available.map(w=>{let score=0,reasons=[];if(w.priority==="yellow"){score+=5;reasons.push("è tra le bottiglie da non dimenticare")}else if(w.priority==="green"){score+=3;reasons.push("è nella sua fase ideale")}else if(w.priority==="orange")score-=1;const isWhite=["Bianco e Bollicine","Bianchi e Bollicine"].includes(w.category);if(white&&isWhite){score+=5;reasons.push("si abbina bene a un'occasione fresca e leggera")}if(red&&!isWhite){score+=5;reasons.push("ha la struttura giusta per piatti saporiti")}if(!white&&!red)score+=2;if(w.vintage){score+=Math.min(Number(w.vintage)||0,9999)/100000}return{w,score,reasons}}).sort((a,b)=>b.score-a.score||a.w.name.localeCompare(b.w.name)).slice(0,3)}
function renderRecommendation(){const query=$("#aiOccasion").value.trim(),choices=recommendWines(query),result=$("#aiRecommendation");if(!choices.length){result.innerHTML='<div class="ai-empty">Non ci sono bottiglie disponibili da consigliare.</div>';return}result.innerHTML=`<div class="recommendations">${choices.map((choice,index)=>{const w=choice.w,reason=choice.reasons.join("; ")||"è una scelta equilibrata per questa occasione",label=index===0?"La mia scelta":`Alternativa ${index+1}`;return`<div class="recommendation"><div class="recommend-photo">${img(w)?`<img src="${esc(img(w))}" alt="${esc(w.name)}">`:"🍷"}</div><div class="recommend-copy"><span class="badge">${label}</span><h3>${esc(w.name)}</h3><p class="muted">${esc(w.producer||w.category)} · ${w.vintage??"S.A."} · ${w.quantity} disponibili</p><p>${esc(reason)}.</p><button class="secondary" data-see-choice="${index}">Vedi scheda</button><button class="winebtn" data-open-choice="${index}">Apri una bottiglia</button></div></div>`}).join("")}</div>`;$$('[data-see-choice]').forEach(b=>b.onclick=()=>showWine(choices[+b.dataset.seeChoice].w.id));$$('[data-open-choice]').forEach(b=>b.onclick=()=>openBottle(choices[+b.dataset.openChoice].w.id));result.scrollIntoView({behavior:"smooth",block:"start"})}
function fileToAnalysisImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const source=new Image();source.onerror=reject;source.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(source.width,source.height)),canvas=document.createElement("canvas");canvas.width=Math.round(source.width*scale);canvas.height=Math.round(source.height*scale);canvas.getContext("2d").drawImage(source,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.82))};source.src=reader.result};reader.readAsDataURL(file)})}
function renderAnalysisResult(data){const duplicate=data.in_cellar_match;return `<div class="analysis-result"><span class="badge">${esc(data.verdict||"Analisi completata")}</span><h3>${esc(data.wine_name||"Vino riconosciuto")}${data.vintage?` ${esc(data.vintage)}`:""}</h3><p class="muted">${esc(data.producer||"")}${data.region?` · ${esc(data.region)}`:""}</p><div class="analysis-score"><b>${esc(data.score??"—")}</b><small>valutazione / 100</small></div><p>${esc(data.summary||"Analisi disponibile.")}</p>${data.market_price?`<p><b>Prezzo indicativo:</b> ${esc(data.market_price)}</p>`:""}${duplicate?`<div class="cellar-match">✓ In cantina: <b>${esc(duplicate.name)}</b> · ${duplicate.quantity} disponibili</div>`:""}<div class="analysis-columns"><div><small>Punti di forza</small><p>${esc((data.strengths||[]).join(" · ")||"—")}</p></div><div><small>Attenzioni</small><p>${esc((data.cautions||[]).join(" · ")||"—")}</p></div></div><p class="buy-advice"><b>Consiglio:</b> ${esc(data.buy_advice||"Valuta prezzo e occasione d'acquisto.")}</p><button class="primary" id="addAnalyzedWine">Aggiungi alla cantina</button></div>`}
async function analyzeBottle(){const result=$("#analysisResult"),button=$("#runAnalysis");if(!pendingAnalysisPhoto)return toast("Scatta o scegli prima la foto della bottiglia.");button.disabled=true;button.textContent="Analizzo etichetta e prezzo…";result.innerHTML='<div class="analysis-loading">Il Sommelier sta leggendo la bottiglia e confrontandola con la cantina…</div>';try{const r=await fetch(`${SUPABASE_URL}/functions/v1/sommelier-analyze`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({image:pendingAnalysisPhoto,price:$("#analysisPrice").value?+$("#analysisPrice").value:null,store:$("#analysisStore").value.trim()||null,cellar:wines.filter(w=>w.quantity>0).map(w=>({id:w.id,name:w.name,producer:w.producer,vintage:w.vintage,quantity:w.quantity,purchase_price:w.purchase_price,market_value_min:w.market_value_min,market_value_max:w.market_value_max}))})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Analisi non disponibile");result.innerHTML=renderAnalysisResult(data);$("#addAnalyzedWine").onclick=()=>{showAdd();$("#newName").value=data.wine_name||"";$("#newProducer").value=data.producer||"";$("#newVintage").value=data.vintage||"";$("#newPrice").value=$("#analysisPrice")?.value||""}}catch(err){result.innerHTML=`<div class="analysis-error"><b>Analisi non completata</b><p>${esc(err.message)}</p></div>`}finally{button.disabled=false;button.textContent="Analizza e confronta"}}
function safeExternalUrl(value){try{const url=new URL(value);return url.protocol==="https:"?url.href:""}catch{return""}}
function renderScoutingResult(data){
  const result=$("#scoutResults"),items=Array.isArray(data.opportunities)?data.opportunities:[];
  if(!items.length){result.innerHTML='<div class="ai-empty">Non ho trovato opportunità abbastanza affidabili. Prova ad ampliare le preferenze.</div>';return}
  const cards=items.map(item=>{
    const url=safeExternalUrl(item.url),price=item.price_eur==null?"Prezzo da verificare":`€${fmt(item.price_eur)}`;
    const seller=item.seller?` · ${esc(item.seller)}`:"",vintage=item.vintage?` ${esc(item.vintage)}`:"";
    const caution=item.caution?`<p class="scout-caution">⚠ ${esc(item.caution)}</p>`:"";
    const link=url?`<a class="winebtn scout-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Vedi offerta</a>`:'<span class="muted">Offerta da verificare</span>';
    return `<article class="scout-result"><div class="scout-score"><b>${esc(item.score)}</b><small>/100</small></div><span class="badge">${esc(item.region||item.style||"Scouting")}</span><h3>${esc(item.name)}${vintage}</h3><p class="muted">${esc(item.producer)} · ${esc(price)}${seller}</p><p>${esc(item.reason)}</p><div class="scout-gap"><b>Perché entra in cantina</b><br>${esc(item.cellar_gap)}</div>${caution}${link}</article>`;
  }).join("");
  const sourceLinks=Array.isArray(data.sources)?data.sources.slice(0,8).map(source=>{const url=safeExternalUrl(source.url);return url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(source.title||"Fonte")}</a>`:""}).join(""):"";
  const sources=sourceLinks?`<details class="scout-sources"><summary>Fonti consultate</summary>${sourceLinks}</details>`:"";
  result.innerHTML=`<div class="scout-summary"><b>Selezione aggiornata</b><p>${esc(data.summary||"Opportunità confrontate con la tua cantina.")}</p></div><div class="scout-results">${cards}</div>${sources}`;
  result.scrollIntoView({behavior:"smooth",block:"start"});
}
function runScouting(){
  const budget=Math.min(500,Math.max(10,+$("#scoutBudget").value||60));
  const interests=$("#scoutInterests").value.trim()||
    "Vini non commerciali, territoriali, con personalità e buon potenziale evolutivo.";

  const available=wines.filter(w=>w.quantity>0);

  const cellar=available.map(w=>{
    const vintage=w.vintage?` ${w.vintage}`:"";
    const producer=w.producer?` — ${w.producer}`:"";
    return `• ${w.name}${vintage}${producer} (${w.quantity} bt)`;
  }).join("\n");

  const prompt=`Agisci come wine scout personale per la mia cantina.

Cerca sul web offerte REALI e attualmente acquistabili in Italia.

BUDGET MASSIMO:
${budget} € a bottiglia.

COSA CERCO:
${interests}

LA MIA CANTINA ATTUALE:
${cellar}

Analizza la composizione della mia cantina e cerca vini che aggiungano realmente qualcosa alla collezione, evitando doppioni inutili.

Privilegia:
- produttori territoriali e poco commerciali
- vini con personalità
- buon potenziale evolutivo
- annate interessanti
- rapporto qualità/prezzo
- territori, vitigni o stili poco rappresentati nella mia cantina

Per ogni proposta verifica online:
- vino e produttore
- annata
- prezzo attuale
- venditore
- disponibilità
- link diretto all'offerta
- finestra di consumo
- perché avrebbe senso nella mia cantina

Proponimi 5 opportunità massimo.

Non inventare prezzi, disponibilità o link. Se un dato non è verificabile, dichiaralo.

Ordina le proposte per interesse rispetto ALLA MIA CANTINA, non semplicemente per fama del vino.`;

  const url="https://chatgpt.com/?q="+encodeURIComponent(prompt);
  window.open(url,"_blank","noopener,noreferrer");
}
function showScoutingWorkspace(){$("#aiWorkspace").innerHTML=`<div class="panel scout-panel"><h3>🔎 Scouting vini</h3><p class="muted">Preparo una ricerca personalizzata usando la tua cantina e la apro direttamente in ChatGPT.</p><div class="scout-fields"><label>Budget massimo per bottiglia <span>€</span><input id="scoutBudget" type="number" min="10" max="500" step="5" inputmode="decimal" value="60"></label><label>Cosa stai cercando?<textarea id="scoutInterests" rows="3" placeholder="Es. Etna Rosso, Barolo non commerciale, bollicine da lungo affinamento…">Vini non commerciali, territoriali, con personalità e buon potenziale evolutivo.</textarea></label></div><button class="primary" id="runScouting">✨ Cerca con ChatGPT</button><p class="scout-note">Prezzi e disponibilità possono cambiare: controlla sempre la pagina del venditore prima dell'acquisto.</p><div id="scoutResults" aria-live="polite"></div></div>`;$("#runScouting").onclick=runScouting;const field=$("#scoutInterests");requestAnimationFrame(()=>field.scrollIntoView({behavior:"smooth",block:"center"}))}
function showView(view){$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('hidden',v.id!==view));$('#addGlobal').classList.toggle('hidden',view!=="cantina")}
function showPriorityInCellar(priority){activePriority=priority;$$('[data-priority]').forEach(x=>x.classList.toggle('active',x.dataset.priority===activePriority));showView("cantina");render();window.scrollTo({top:0,behavior:"smooth"})}
function aiWorkspace(mode){if(mode==="open"){$("#aiWorkspace").innerHTML=`<div class="panel ai-open-panel"><h3>🍷 Cosa apro?</h3><p class="muted">Raccontami cena, piatto o occasione: userò disponibilità, priorità e abbinamento.</p><textarea id="aiOccasion" placeholder="Es. Stasera grigliata per 6 persone…"></textarea><button class="primary" id="askSommelier">Chiedi al Sommelier</button><div id="aiRecommendation" aria-live="polite"></div></div>`;const field=$("#aiOccasion");$("#askSommelier").onclick=renderRecommendation;field.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")renderRecommendation};field.focus({preventScroll:true});requestAnimationFrame(()=>field.scrollIntoView({behavior:"smooth",block:"center"}))}else if(mode==="analyze"){pendingAnalysisPhoto=null;$("#aiWorkspace").innerHTML=`<div class="panel analyze-panel"><h3>📷 Analizza / Acquista</h3><p class="muted">Fotografa bene l'etichetta. Il Sommelier riconosce il vino, valuta il prezzo e controlla se è già presente in cantina.</p><div class="camera-box" id="analysisCamera"><div class="cam">📷</div><b>Fotografa o scegli la bottiglia</b><p>Etichetta frontale, luce uniforme, niente riflessi.</p></div><div id="analysisPreview"></div><div class="analysis-fields"><label>Prezzo proposto € <input id="analysisPrice" type="number" min="0" step="0.01" inputmode="decimal" placeholder="Facoltativo"></label><label>Negozio o sito <input id="analysisStore" placeholder="Facoltativo"></label></div><button class="primary" id="runAnalysis">Analizza e confronta</button><div id="analysisResult" aria-live="polite"></div></div>`;$("#analysisCamera").innerHTML=`<div class="cam">📷</div><b>Foto della bottiglia</b><p>Scatta una foto oppure sceglila dalla libreria.</p><button type="button" class="secondary" id="analysisChoosePhoto">📷 Scegli foto</button>`;
$("#analysisChoosePhoto").onclick=e=>{
  e.stopPropagation();
  $("#galleryInput").click();
};;$("#runAnalysis").onclick=analyzeBottle;setTimeout(()=>{const p=$("#aiWorkspace .analyze-panel");if(p)window.scrollTo({top:p.getBoundingClientRect().top+window.scrollY-12,behavior:"smooth"})},150)}else $("#aiWorkspace").innerHTML=`<div class="panel"><h3>🔎 Scouting</h3><p class="muted">Il feed è predisposto per imparare da approfondimenti, salvataggi, acquisti e scarti.</p><div class="scout-card"><div class="fakephoto">🍷</div><div class="scoutbody"><span class="badge">Feed personale</span><h3>Le opportunità compariranno qui</h3><p class="muted">Tap per approfondire · swipe a sinistra per scartare · ♡ per salvare.</p></div></div></div>`}
function toast(msg){$("#toast").innerHTML=msg;$("#toast").classList.remove("hidden");setTimeout(()=>$("#toast").classList.add("hidden"),5500)}function exportBackup(){const blob=new Blob([JSON.stringify({exported:new Date().toISOString(),wines,history},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="Cantina_De_Pasquale_backup.json";a.click();URL.revokeObjectURL(a.href)}async function login(email,password){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email,password})});if(!r.ok)throw new Error("Email o password non corrette.");saveSession(await r.json())}function showApp(){$("#loginScreen").classList.add("hidden");$("#app").classList.remove("hidden")}function showLogin(){$("#app").classList.add("hidden");$("#loginScreen").classList.remove("hidden")}
async function start(){session=cachedSession();if(session){showApp();try{await loadCloud()}catch{let restored=false;if(navigator.onLine){try{if(await refreshSession()){await loadCloud();restored=true}}catch{}}if(!restored&&!loadCache()){if(navigator.onLine){saveSession(null);showLogin()}else{setSync("Offline",true);toast("Primo accesso non disponibile senza connessione.")}}}}else showLogin();$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginMsg").textContent="Accesso…";try{await login($("#email").value.trim(),$("#password").value);showApp();await loadCloud();$("#loginMsg").textContent=""}catch(err){$("#loginMsg").textContent=err.message}};$("#search").oninput=render;$$('[data-priority]').forEach(b=>b.onclick=()=>{activePriority=activePriority===b.dataset.priority?null:b.dataset.priority;$$('[data-priority]').forEach(x=>x.classList.toggle('active',x.dataset.priority===activePriority));render()});$$('[data-priority-link]').forEach(b=>b.onclick=()=>showPriorityInCellar(b.dataset.priorityLink));$$('[data-type]').forEach(b=>b.onclick=()=>{activeType=b.dataset.type;$$('[data-type]').forEach(x=>x.classList.toggle('active',x===b));render()});$$('.bottom-nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-ai]').forEach(b=>b.onclick=()=>aiWorkspace(b.dataset.ai));$("#chatBar").onclick=()=>aiWorkspace("open");$("#addGlobal").onclick=()=>showAdd();$("#closeModal").onclick=closeModal;$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};$("#exportBtn").onclick=exportBackup;$("#cameraInput").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f),p=$("#photoPreview"),analysis=$("#analysisPreview");if(p)p.innerHTML=`<img src="${url}" style="width:100%;max-height:220px;object-fit:contain;border-radius:16px;margin-bottom:10px">`;if(analysis){analysis.innerHTML=`<img src="${url}" alt="Bottiglia da analizzare">`;try{pendingAnalysisPhoto=await fileToAnalysisImage(f);toast("Foto pronta per l'analisi.")}catch{pendingAnalysisPhoto=null;toast("Non sono riuscito a preparare questa foto.")}}else toast("Foto acquisita. Il riconoscimento AI verrà eseguito dal motore Sommelier.");e.target.value=""};$("#galleryInput").onchange=$("#cameraInput").onchange;window.addEventListener("online",()=>session&&loadCloud().catch(()=>{loadCache();setSync("Offline",true)}));window.addEventListener("offline",()=>{loadCache();setSync("Offline",true)});if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js")}
const legacyAiWorkspace=aiWorkspace;aiWorkspace=mode=>mode==="scouting"?showScoutingWorkspace():legacyAiWorkspace(mode);
start().then(()=>{$("#sort").onchange=e=>{activeSort=e.target.value;render()};["#historyRating","#historyRegion","#historyCategory","#historyYear"].forEach(id=>$(id).onchange=renderHistory);$$('[data-history-type]').forEach(b=>b.onclick=()=>{activeHistoryType=b.dataset.historyType;$$('[data-history-type]').forEach(x=>x.classList.toggle('active',x===b));renderHistory()})});
